- name: "apt-get update" 
  apt:
    update_cache: yes

- name: "python3" 
  apt:
    name: python3

- name: "python3-pip"
  apt:
    name: python3-pip

- name: "rasp-config"
  get_url:
    url: https://archive.raspberrypi.org/debian/pool/main/r/raspi-config/raspi-config_20200601_all.deb 
    dest: /etc/ansible/file/raspi-config_20200601_all.deb

- name: "instalando rasp-config" 
  apt: 
    deb: /etc/ansible/file/raspi-config_20200601_all.deb

